# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

parameters:

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true
        autoconfigure: true

    # Automatically register classes from src/ as services
    App\:
        resource: '../src/'

    # Explicit configuration for the JWT decoded listener
    App\EventListener\JwtDecodedListener:
        tags:
            - name: kernel.event_listener
              event: lexik_jwt_authentication.on_jwt_decoded
              method: onJWTDecoded