api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        route_prefix: /api
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
