<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713094137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE adress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, street VARCHAR(255) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5CECC7BE8BAC62AF ON adress (city_id)');
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, commune VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE city_postal_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city_id INT NOT NULL, postal_code_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C92CFD798BAC62AF ON city_postal_code (city_id)');
        $this->addSql('CREATE INDEX IDX_C92CFD79BDBA6A61 ON city_postal_code (postal_code_id)');
        $this->addSql('CREATE TABLE fleet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, moral_entity_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A05E1E47A76ED395 ON fleet (user_id)');
        $this->addSql('CREATE INDEX IDX_A05E1E47AF0856B6 ON fleet (moral_entity_id)');
        $this->addSql('CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE group_user (group_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (group_id, user_id))');
        $this->addSql('CREATE INDEX IDX_A4C98D39FE54D947 ON group_user (group_id)');
        $this->addSql('CREATE INDEX IDX_A4C98D39A76ED395 ON group_user (user_id)');
        $this->addSql('CREATE TABLE group_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, groups_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A36222A8F373DCF ON group_member (groups_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, is_reported BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sender_id INT NOT NULL, receiver_id INT DEFAULT NULL, group_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FCD53EDB6 ON message (receiver_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FFE54D947 ON message (group_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FA5BC2E0E ON message (trip_id)');
        $this->addSql('CREATE TABLE moral_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, siret INT NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(255) NOT NULL, address_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A93C054F5B7AF75 ON moral_entity (address_id)');
        $this->addSql('CREATE TABLE moral_entity_user (moral_entity_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (moral_entity_id, user_id))');
        $this->addSql('CREATE INDEX IDX_D4699228AF0856B6 ON moral_entity_user (moral_entity_id)');
        $this->addSql('CREATE INDEX IDX_D4699228A76ED395 ON moral_entity_user (user_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, notification_type VARCHAR(255) DEFAULT \'PERSONNAL\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, receiver_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CACD53EDB6 ON notification (receiver_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BF5476CAA5BC2E0E ON notification (trip_id)');
        $this->addSql('CREATE TABLE postal_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA98E3768BAC62AF ON postal_code (city_id)');
        $this->addSql('CREATE TABLE preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, report_status VARCHAR(255) NOT NULL, moderator_notes VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reporter_id INT NOT NULL, reported_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_C42F778494BDEEB6 ON report (reported_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_reported BOOLEAN DEFAULT false NOT NULL, comment VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT NOT NULL, reviewed_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C6F675F31B ON review (author_id)');
        $this->addSql('CREATE INDEX IDX_794381C65254E55 ON review (reviewed_id)');
        $this->addSql('CREATE INDEX IDX_794381C6A5BC2E0E ON review (trip_id)');
        $this->addSql('CREATE TABLE traveler (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, traveler_role VARCHAR(255) NOT NULL, traveler_status VARCHAR(255) DEFAULT \'PENDING\' NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6841F216A5BC2E0E ON traveler (trip_id)');
        $this->addSql('CREATE INDEX IDX_6841F216A76ED395 ON traveler (user_id)');
        $this->addSql('CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, estimated_arrival_datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_seat INT NOT NULL, available_seat INT NOT NULL, total_price DOUBLE PRECISION NOT NULL, price_per_passenger DOUBLE PRECISION NOT NULL, average_rating DOUBLE PRECISION NOT NULL, is_women_only BOOLEAN NOT NULL, trip_status VARCHAR(255) NOT NULL, trip_creator_role VARCHAR(255) NOT NULL, available_seats INT DEFAULT 3 NOT NULL, trip_status_default VARCHAR(255) DEFAULT \'PUBLISHED\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creator_id INT NOT NULL, vehicle_id INT NOT NULL, departure_address_id INT NOT NULL, arrival_address_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7656F53B61220EA6 ON trip (creator_id)');
        $this->addSql('CREATE INDEX IDX_7656F53B545317D1 ON trip (vehicle_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7656F53B2B1957E1 ON trip (departure_address_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7656F53BA26B1FFE ON trip (arrival_address_id)');
        $this->addSql('CREATE TABLE trip_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, trip_id INT NOT NULL, preference_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A87B6B45A5BC2E0E ON trip_preference (trip_id)');
        $this->addSql('CREATE INDEX IDX_A87B6B45D81022C0 ON trip_preference (preference_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, gender VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, picture_url VARCHAR(255) DEFAULT NULL, bio VARCHAR(255) DEFAULT NULL, accept_call BOOLEAN DEFAULT false NOT NULL, average_rating DOUBLE PRECISION DEFAULT 0, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1087D9EA76ED395 ON user_info (user_id)');
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, user_info_id INT NOT NULL, preference_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA0E76BF586DFF2 ON user_preference (user_info_id)');
        $this->addSql('CREATE INDEX IDX_FA0E76BFD81022C0 ON user_preference (preference_id)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, has_ac BOOLEAN NOT NULL, consumption_liter_per_100km DOUBLE PRECISION NOT NULL, seat INT NOT NULL, vehicle_state VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, picture_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fleet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B80E4864B061DF9 ON vehicle (fleet_id)');
        $this->addSql('CREATE TABLE waypoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estimated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description VARCHAR(255) NOT NULL, trip_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3DC5881A5BC2E0E ON waypoint (trip_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3DC5881F5B7AF75 ON waypoint (address_id)');
        $this->addSql('ALTER TABLE adress ADD CONSTRAINT FK_5CECC7BE8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_postal_code ADD CONSTRAINT FK_C92CFD798BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_postal_code ADD CONSTRAINT FK_C92CFD79BDBA6A61 FOREIGN KEY (postal_code_id) REFERENCES postal_code (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47AF0856B6 FOREIGN KEY (moral_entity_id) REFERENCES moral_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE group_user ADD CONSTRAINT FK_A4C98D39FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_user ADD CONSTRAINT FK_A4C98D39A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_member ADD CONSTRAINT FK_A36222A8F373DCF FOREIGN KEY (groups_id) REFERENCES "group" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FFE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id)');
        $this->addSql('ALTER TABLE moral_entity ADD CONSTRAINT FK_5A93C054F5B7AF75 FOREIGN KEY (address_id) REFERENCES adress (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moral_entity_user ADD CONSTRAINT FK_D4699228AF0856B6 FOREIGN KEY (moral_entity_id) REFERENCES moral_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moral_entity_user ADD CONSTRAINT FK_D4699228A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id)');
        $this->addSql('ALTER TABLE postal_code ADD CONSTRAINT FK_EA98E3768BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778494BDEEB6 FOREIGN KEY (reported_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C65254E55 FOREIGN KEY (reviewed_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id)');
        $this->addSql('ALTER TABLE traveler ADD CONSTRAINT FK_6841F216A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE traveler ADD CONSTRAINT FK_6841F216A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B61220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B2B1957E1 FOREIGN KEY (departure_address_id) REFERENCES adress (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53BA26B1FFE FOREIGN KEY (arrival_address_id) REFERENCES adress (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_preference ADD CONSTRAINT FK_A87B6B45A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_preference ADD CONSTRAINT FK_A87B6B45D81022C0 FOREIGN KEY (preference_id) REFERENCES preference (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT FK_B1087D9EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_FA0E76BF586DFF2 FOREIGN KEY (user_info_id) REFERENCES user_info (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_FA0E76BFD81022C0 FOREIGN KEY (preference_id) REFERENCES preference (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4864B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE waypoint ADD CONSTRAINT FK_B3DC5881A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE waypoint ADD CONSTRAINT FK_B3DC5881F5B7AF75 FOREIGN KEY (address_id) REFERENCES adress (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE adress DROP CONSTRAINT FK_5CECC7BE8BAC62AF');
        $this->addSql('ALTER TABLE city_postal_code DROP CONSTRAINT FK_C92CFD798BAC62AF');
        $this->addSql('ALTER TABLE city_postal_code DROP CONSTRAINT FK_C92CFD79BDBA6A61');
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT FK_A05E1E47A76ED395');
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT FK_A05E1E47AF0856B6');
        $this->addSql('ALTER TABLE group_user DROP CONSTRAINT FK_A4C98D39FE54D947');
        $this->addSql('ALTER TABLE group_user DROP CONSTRAINT FK_A4C98D39A76ED395');
        $this->addSql('ALTER TABLE group_member DROP CONSTRAINT FK_A36222A8F373DCF');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCD53EDB6');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FFE54D947');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FA5BC2E0E');
        $this->addSql('ALTER TABLE moral_entity DROP CONSTRAINT FK_5A93C054F5B7AF75');
        $this->addSql('ALTER TABLE moral_entity_user DROP CONSTRAINT FK_D4699228AF0856B6');
        $this->addSql('ALTER TABLE moral_entity_user DROP CONSTRAINT FK_D4699228A76ED395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CACD53EDB6');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA5BC2E0E');
        $this->addSql('ALTER TABLE postal_code DROP CONSTRAINT FK_EA98E3768BAC62AF');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778494BDEEB6');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C65254E55');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6A5BC2E0E');
        $this->addSql('ALTER TABLE traveler DROP CONSTRAINT FK_6841F216A5BC2E0E');
        $this->addSql('ALTER TABLE traveler DROP CONSTRAINT FK_6841F216A76ED395');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B61220EA6');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B545317D1');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B2B1957E1');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53BA26B1FFE');
        $this->addSql('ALTER TABLE trip_preference DROP CONSTRAINT FK_A87B6B45A5BC2E0E');
        $this->addSql('ALTER TABLE trip_preference DROP CONSTRAINT FK_A87B6B45D81022C0');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT FK_B1087D9EA76ED395');
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_FA0E76BF586DFF2');
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_FA0E76BFD81022C0');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4864B061DF9');
        $this->addSql('ALTER TABLE waypoint DROP CONSTRAINT FK_B3DC5881A5BC2E0E');
        $this->addSql('ALTER TABLE waypoint DROP CONSTRAINT FK_B3DC5881F5B7AF75');
        $this->addSql('DROP TABLE adress');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE city_postal_code');
        $this->addSql('DROP TABLE fleet');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_user');
        $this->addSql('DROP TABLE group_member');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE moral_entity');
        $this->addSql('DROP TABLE moral_entity_user');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE postal_code');
        $this->addSql('DROP TABLE preference');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE traveler');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE trip_preference');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_info');
        $this->addSql('DROP TABLE user_preference');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE waypoint');
    }
}
